import {
  User, Target, FileText, Building2, DollarSign, Calendar,
  Award, BookOpen, Clock, Settings, BarChart, Users, Briefcase,
  GraduationCap, Home, LayoutGrid, ClipboardList, TrendingUp,
  Wallet, Shield, HelpCircle, CalendarDays, UserCheck, Heart,
  Star, Check, AlertCircle, Bell, FileCheck, Folder, FolderOpen,
  Mail, MapPin, Phone, Globe, Link, Eye, Edit, Trash2, Plus,
  Minus, Search, Filter, Download, Upload, Share, Copy, Save,
  Undo, Redo, ArrowLeft, ArrowRight, ArrowUp, ArrowDown,
  ChevronLeft, ChevronRight, ChevronUp, ChevronDown, Menu,
  MoreHorizontal, MoreVertical, Grip, GripVertical, GripHorizontal,
  Columns, Rows, List, Grid, Table, PieChart, LineChart, BarChart2,
  Activity, Zap, Flame, Sparkles, Wand2, Bot, Brain,
  Lightbulb, Key, Lock, Unlock, LogIn, LogOut, UserPlus, UserMinus,
  UserX, UserCog, Users2, Building, Factory, Store, Warehouse,
  Timer, Hourglass, History, Repeat,
  RefreshCw, RotateCw, RotateCcw, Power, Play, Pause,
  SkipForward, SkipBack, FastForward, Rewind, Volume2,
  VolumeX, Mic, MicOff, Video, VideoOff, Camera, Image,
  ImagePlus, Palette, Paintbrush, Pen, Pencil, Highlighter,
  Eraser, Scissors, Crop, ZoomIn, ZoomOut, Maximize, Minimize,
  Fullscreen, Monitor, Laptop, Tablet, Smartphone, Tv, Radio,
  Headphones, Speaker, Printer, HardDrive, Database,
  Server, Cloud, CloudUpload, CloudDownload, CloudOff, Wifi,
  WifiOff, Signal, Satellite, Cast, Airplay, Bluetooth,
  Cable, Plug, Battery, BatteryCharging, BatteryLow, BatteryFull,
  Sun, Moon, Sunrise, Sunset, CloudSun, CloudMoon, CloudRain,
  CloudSnow, CloudLightning, Umbrella, Wind, Thermometer, Droplet,
  Leaf, TreeDeciduous, Flower, Mountain, Waves, Fish, Bug,
  PawPrint, Cat, Dog, Bird, Hammer, Wrench, Ruler,
  LayoutDashboard, PanelLeft, PanelRight, PanelTop, PanelBottom,
  SidebarOpen, SidebarClose, Layers, Component, Blocks, Puzzle,
  Shapes, Square, Circle, Triangle, Pentagon, Hexagon, Octagon,
  Diamond, Gem, Sparkle,
  PartyPopper, Cake, Pizza, Coffee, Wine, Beer,
  Utensils, ChefHat, Milk,
  BookMarked, Bookmark, BookText,
  Library, School, Presentation, Kanban,
  CalendarCheck, CalendarX, CalendarPlus,
  CalendarMinus, CalendarRange, CalendarSearch,
  ClipboardCheck, ClipboardX, ClipboardCopy,
  NotebookPen, NotebookText,
  StickyNote, FileSpreadsheet, FileJson, FileCode, FileTerminal,
  FileCog, FileHeart, FileLock, FileKey, FileSearch,
  FileX, FilePlus, FileMinus, Files,
  FolderPlus, FolderMinus, FolderX, FolderCheck, FolderSearch,
  FolderInput, FolderOutput, FolderSync, FolderCog, FolderLock,
  FolderKey, FolderHeart, FolderArchive, FolderGit, FolderGit2,
  FolderTree, FolderRoot, FolderKanban, Network, Workflow,
  GitBranch, GitCommit, GitMerge, GitPullRequest, GitFork,
  CircleDot, CircleDotDashed, CircleDashed, CircleSlash,
  CircleOff, CircleCheck, CircleX, CirclePlus, CircleMinus,
  CircleHelp, CircleAlert, CircleUser, CircleUserRound, BadgeCheck,
  BadgeX, BadgeAlert, BadgeHelp, BadgeInfo, BadgePlus, BadgeMinus,
  BadgePercent, BadgeDollarSign, ShieldQuestion,
  // Leave Management icons
  Banknote, Baby, ShieldCheck, Ban, Percent, BarChart3, Calculator,
  CheckCircle,
  // Payroll icons
  Receipt, Coins, PiggyBank, ArrowRightLeft, Sliders, Flag,
  Link2, Settings2, Archive, CreditCard, Landmark, HandCoins,
  type LucideIcon,
} from "lucide-react";

// Registry mapping icon names to components
export const iconRegistry: Record<string, LucideIcon> = {
  User,
  Target,
  FileText,
  Building2,
  DollarSign,
  Calendar,
  Award,
  BookOpen,
  Clock,
  Settings,
  BarChart,
  Users,
  Briefcase,
  GraduationCap,
  Home,
  LayoutGrid,
  ClipboardList,
  TrendingUp,
  Wallet,
  Shield,
  HelpCircle,
  CalendarDays,
  UserCheck,
  Heart,
  Star,
  Check,
  AlertCircle,
  Bell,
  FileCheck,
  Folder,
  FolderOpen,
  Mail,
  MapPin,
  Phone,
  Globe,
  Link,
  Eye,
  Edit,
  Trash2,
  Plus,
  Minus,
  Search,
  Filter,
  Download,
  Upload,
  Share,
  Copy,
  Save,
  Undo,
  Redo,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Menu,
  MoreHorizontal,
  MoreVertical,
  Grip,
  GripVertical,
  GripHorizontal,
  Columns,
  Rows,
  List,
  Grid,
  Table,
  PieChart,
  LineChart,
  BarChart2,
  Activity,
  Zap,
  Flame,
  Sparkles,
  Wand2,
  Bot,
  Brain,
  Lightbulb,
  Key,
  Lock,
  Unlock,
  LogIn,
  LogOut,
  UserPlus,
  UserMinus,
  UserX,
  UserCog,
  Users2,
  Building,
  Factory,
  Store,
  Warehouse,
  LayoutDashboard,
  Layers,
  Component,
  Blocks,
  Network,
  Workflow,
  BadgeCheck,
  Timer,
  Hourglass,
  History,
  Database,
  Server,
  Cloud,
  // Time & Attendance icons (new additions - others already present above)
  Repeat,
  RefreshCw,
  Ruler,
  Sunrise,
  Sunset,
  Plug,
  Sun,
  Moon,
  // Leave Management icons
  Banknote,
  Baby,
  ShieldCheck,
  Ban,
  Percent,
  BarChart3,
  Calculator,
  CheckCircle,
  CalendarPlus,
  CalendarCheck,
  RotateCcw,
  PartyPopper,
  // Payroll icons
  Receipt,
  Coins,
  PiggyBank,
  ArrowRightLeft,
  Sliders,
  Flag,
  Link2,
  Settings2,
  Archive,
  CreditCard,
  Landmark,
  HandCoins,
  FileSpreadsheet,
};

/**
 * Get a Lucide icon component by its name
 */
export function getIconByName(name: string): LucideIcon | undefined {
  return iconRegistry[name];
}

/**
 * Get the string name for a Lucide icon component
 */
export function getIconName(icon: LucideIcon): string | undefined {
  for (const [name, component] of Object.entries(iconRegistry)) {
    if (component === icon) {
      return name;
    }
  }
  return undefined;
}

/**
 * Check if an icon name exists in the registry
 */
export function hasIcon(name: string): boolean {
  return name in iconRegistry;
}
