export { MexicanCompanySetup } from './MexicanCompanySetup';
export { MexicanEmployeeData } from './MexicanEmployeeData';
export { CFDIDashboard } from './CFDIDashboard';
export { MexicanPayslipTemplate } from './MexicanPayslipTemplate';
export { MexicanPayrollRun } from './MexicanPayrollRun';
export { SUAIDSEGenerator } from './SUAIDSEGenerator';
export { MexicanBenefitsCalculator } from './MexicanBenefitsCalculator';
export { INFONAVITManager } from './INFONAVITManager';
export { FONACOTManager } from './FONACOTManager';
export { MexicanAnnualISR } from './MexicanAnnualISR';
export { TaxCertificates } from './TaxCertificates';
export { MexicanPayrollAnalytics } from './MexicanPayrollAnalytics';
export { ComplianceCalendar } from './ComplianceCalendar';
export { PayrollAdjustments } from './PayrollAdjustments';

// Phase 11 - Mexico-specific features
export { EFirmaIntegration } from './EFirmaIntegration';
export { STPSCompliance } from './STPSCompliance';
export { REPSERegistry } from './REPSERegistry';
export { ISNByState } from './ISNByState';
export { OutsourcingReformCompliance } from './OutsourcingReformCompliance';
export { SATAuditSupport } from './SATAuditSupport';
export { MexicanUnionManagement } from './MexicanUnionManagement';
export { EmployeeSelfService } from './EmployeeSelfService';
export { MultiPeriodComparison } from './MultiPeriodComparison';
export { AuditTrail } from './AuditTrail';
export { PACIntegration } from './PACIntegration';
export { PayrollSimulations } from './PayrollSimulations';
export { BatchOperations } from './BatchOperations';
export { VacationPTUManager } from './VacationPTUManager';
export { SeveranceCalculator } from './SeveranceCalculator';
export { PayrollTemplates } from './PayrollTemplates';
export { IntegrationWebhooks } from './IntegrationWebhooks';

// Phase 12 - Mexico Advanced Compliance & AI
export { SATXMLValidator } from './SATXMLValidator';
export { IDSEAutomation } from './IDSEAutomation';
export { SUAAdvancedGenerator } from './SUAAdvancedGenerator';
export { EmployerSocialContributions } from './EmployerSocialContributions';
export { PayrollAnomalyDetection } from './PayrollAnomalyDetection';
