import { Card, CardContent } from '@/components/ui/card';

export function LndTroubleshootingCommonSetup() { return (<section id="sec-9-1" data-manual-anchor="sec-9-1"><h2 className="text-2xl font-bold mb-2">9.1 Common Setup Issues</h2><Card><CardContent className="pt-6"><p>Resolve common configuration errors during L&D module setup.</p></CardContent></Card></section>); }
export function LndTroubleshootingCourseVisibility() { return (<section id="sec-9-2" data-manual-anchor="sec-9-2"><h2 className="text-2xl font-bold mb-2">9.2 Course Visibility Issues</h2><Card><CardContent className="pt-6"><p>Troubleshoot courses not appearing in catalog or for specific users.</p></CardContent></Card></section>); }
export function LndTroubleshootingProgressTracking() { return (<section id="sec-9-3" data-manual-anchor="sec-9-3"><h2 className="text-2xl font-bold mb-2">9.3 Progress Tracking Issues</h2><Card><CardContent className="pt-6"><p>Resolve lesson completion and progress percentage discrepancies.</p></CardContent></Card></section>); }
export function LndTroubleshootingQuizIssues() { return (<section id="sec-9-4" data-manual-anchor="sec-9-4"><h2 className="text-2xl font-bold mb-2">9.4 Quiz Issues</h2><Card><CardContent className="pt-6"><p>Fix quiz scoring, timing, and submission problems.</p></CardContent></Card></section>); }
export function LndTroubleshootingCertificateIssues() { return (<section id="sec-9-5" data-manual-anchor="sec-9-5"><h2 className="text-2xl font-bold mb-2">9.5 Certificate Issues</h2><Card><CardContent className="pt-6"><p>Troubleshoot certificate generation and delivery failures.</p></CardContent></Card></section>); }
export function LndTroubleshootingIntegration() { return (<section id="sec-9-6" data-manual-anchor="sec-9-6"><h2 className="text-2xl font-bold mb-2">9.6 Integration Troubleshooting</h2><Card><CardContent className="pt-6"><p>Resolve cross-module integration and SCORM tracking issues.</p></CardContent></Card></section>); }
export function LndTroubleshootingBestPractices() { return (<section id="sec-9-7" data-manual-anchor="sec-9-7"><h2 className="text-2xl font-bold mb-2">9.7 Best Practices</h2><Card><CardContent className="pt-6"><p>Recommended practices for L&D administration and maintenance.</p></CardContent></Card></section>); }
