import { Brain, Info, ShieldCheck, Clock, AlertTriangle } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { formatDateForDisplay } from "@/utils/dateUtils";

interface AITransparencyBannerProps {
  modelName?: string;
  lastAnalysisDate?: string;
  confidenceLevel?: "low" | "medium" | "high";
  isoCompliant?: boolean;
  humanReviewRequired?: boolean;
  analyzedCount?: number;
}

export function AITransparencyBanner({
  modelName = "HRplus AI Risk Analyzer",
  lastAnalysisDate,
  confidenceLevel = "medium",
  isoCompliant = true,
  humanReviewRequired = false,
  analyzedCount,
}: AITransparencyBannerProps) {
  const getConfidenceColor = () => {
    switch (confidenceLevel) {
      case "high":
        return "bg-success/10 text-success border-success/20";
      case "medium":
        return "bg-warning/10 text-warning border-warning/20";
      case "low":
        return "bg-destructive/10 text-destructive border-destructive/20";
    }
  };

  return (
    <Alert className="bg-muted/50 border-primary/20">
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
            <Brain className="h-5 w-5 text-primary" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <span className="font-medium text-sm">AI-Powered Analysis</span>
              <Tooltip>
                <TooltipTrigger>
                  <Info className="h-3.5 w-3.5 text-muted-foreground" />
                </TooltipTrigger>
                <TooltipContent className="max-w-sm">
                  <p className="text-sm">
                    This analysis is generated by {modelName}, an AI system designed to identify 
                    performance risks. All AI-generated insights require human review before action.
                  </p>
                </TooltipContent>
              </Tooltip>
            </div>
            <p className="text-xs text-muted-foreground">
              Model: {modelName}
              {lastAnalysisDate && (
                <span className="ml-2">
                  • Last run: {formatDateForDisplay(lastAnalysisDate, "MMM d, yyyy h:mm a")}
                </span>
              )}
              {analyzedCount !== undefined && (
                <span className="ml-2">
                  • {analyzedCount} employees analyzed
                </span>
              )}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 flex-wrap">
          {/* Confidence Badge */}
          <Badge variant="outline" className={getConfidenceColor()}>
            {confidenceLevel.charAt(0).toUpperCase() + confidenceLevel.slice(1)} Confidence
          </Badge>

          {/* ISO Compliance Badge */}
          {isoCompliant && (
            <Tooltip>
              <TooltipTrigger>
                <Badge variant="outline" className="bg-primary/5 border-primary/20 gap-1">
                  <ShieldCheck className="h-3 w-3" />
                  ISO 42001
                </Badge>
              </TooltipTrigger>
              <TooltipContent>
                <p className="text-sm">This AI system complies with ISO 42001 AI Management System standards</p>
              </TooltipContent>
            </Tooltip>
          )}

          {/* Human Review Required Badge */}
          {humanReviewRequired && (
            <Badge variant="outline" className="bg-warning/10 text-warning border-warning/20 gap-1">
              <AlertTriangle className="h-3 w-3" />
              Human Review Required
            </Badge>
          )}
        </div>
      </div>
    </Alert>
  );
}
