import { Card, CardContent } from '@/components/ui/card';

export function LndAnalyticsDashboard() { return (<section id="sec-7-1" data-manual-anchor="sec-7-1"><h2 className="text-2xl font-bold mb-2">7.1 Analytics Dashboard</h2><Card><CardContent className="pt-6"><p>Central hub for training analytics with KPIs and trend visualization.</p></CardContent></Card></section>); }
export function LndAnalyticsLearnerProgress() { return (<section id="sec-7-2" data-manual-anchor="sec-7-2"><h2 className="text-2xl font-bold mb-2">7.2 Learner Progress Reports</h2><Card><CardContent className="pt-6"><p>Track individual and cohort learning progress across courses.</p></CardContent></Card></section>); }
export function LndAnalyticsCourseEffectiveness() { return (<section id="sec-7-3" data-manual-anchor="sec-7-3"><h2 className="text-2xl font-bold mb-2">7.3 Course Effectiveness</h2><Card><CardContent className="pt-6"><p>Measure course quality through completion rates, scores, and feedback.</p></CardContent></Card></section>); }
export function LndAnalyticsBudgetUtilization() { return (<section id="sec-7-4" data-manual-anchor="sec-7-4"><h2 className="text-2xl font-bold mb-2">7.4 Budget Utilization</h2><Card><CardContent className="pt-6"><p>Track training spend against budgets by department and category.</p></CardContent></Card></section>); }
export function LndAnalyticsComplianceReporting() { return (<section id="sec-7-5" data-manual-anchor="sec-7-5"><h2 className="text-2xl font-bold mb-2">7.5 Compliance Reporting</h2><Card><CardContent className="pt-6"><p>Generate compliance status reports for regulatory submissions.</p></CardContent></Card></section>); }
export function LndAnalyticsManagerTeamView() { return (<section id="sec-7-6" data-manual-anchor="sec-7-6"><h2 className="text-2xl font-bold mb-2">7.6 Manager Team View</h2><Card><CardContent className="pt-6"><p>Manager dashboard for team training status and development tracking.</p></CardContent></Card></section>); }
export function LndAnalyticsAIPoweredBI() { return (<section id="sec-7-7" data-manual-anchor="sec-7-7"><h2 className="text-2xl font-bold mb-2">7.7 AI-Powered BI Reports</h2><Card><CardContent className="pt-6"><p>Natural language querying and AI-generated training insights.</p></CardContent></Card></section>); }
export function LndAnalyticsKirkpatrick() { return (<section id="sec-7-8" data-manual-anchor="sec-7-8"><h2 className="text-2xl font-bold mb-2">7.8 Kirkpatrick Model Reporting</h2><Card><CardContent className="pt-6"><p>Four-level evaluation framework: Reaction, Learning, Behavior, Results.</p></CardContent></Card></section>); }
export function LndAnalyticsROI() { return (<section id="sec-7-9" data-manual-anchor="sec-7-9"><h2 className="text-2xl font-bold mb-2">7.9 ROI Analysis</h2><Card><CardContent className="pt-6"><p>Calculate return on training investment with cost-benefit analysis.</p></CardContent></Card></section>); }
