// Module mapping for audit logs - maps entity types to their parent modules

export const moduleMapping: Record<string, string> = {
  // Admin & Security Module
  'audit_logs': 'Admin',
  'company': 'Admin',
  'companies': 'Admin',
  'companies_list': 'Admin',
  'company_groups': 'Admin',
  'role': 'Admin',
  'roles': 'Admin',
  'roles_list': 'Admin',
  'user': 'Admin',
  'users': 'Admin',
  'users_list': 'Admin',
  'lookup_value': 'Admin',
  'lookup_values': 'Admin',
  'implementation_step': 'Admin',
  'settings': 'Admin',
  'custom_fields': 'Admin',
  'letter_templates': 'Admin',
  'onboarding_templates': 'Admin',
  'policy_documents': 'Admin',
  'reminders': 'Admin',
  'scheduled_reports': 'Admin',
  'workflow_templates': 'Admin',
  'approval_delegations': 'Admin',
  'announcements': 'Admin',
  'company_documents': 'Admin',
  'company_tags': 'Admin',
  'company_values': 'Admin',
  'currencies': 'Admin',
  'translations': 'Admin',
  'permissions': 'Admin',
  'mfa_settings': 'Admin',
  'password_policies': 'Admin',
  'sso_settings': 'Admin',
  'session': 'Admin',
  'sessions': 'Admin',
  'ai_usage': 'Admin',
  'ai_governance': 'Admin',
  'ai_security': 'Admin',
  'access_requests': 'Admin',
  'bulk_import': 'Admin',
  'helpdesk': 'Admin',
  'knowledge_base': 'Admin',
  'client': 'Admin',
  'clients': 'Admin',
  'demo_management': 'Admin',
  'territories': 'Admin',

  // Workforce Module
  'employee': 'Workforce',
  'employees': 'Workforce',
  'employees_list': 'Workforce',
  'employee_profile': 'Workforce',
  'employee_transaction': 'Workforce',
  'employee_transactions': 'Workforce',
  'employee_assignments': 'Workforce',
  'job': 'Workforce',
  'jobs': 'Workforce',
  'jobs_list': 'Workforce',
  'job_family': 'Workforce',
  'job_families': 'Workforce',
  'position': 'Workforce',
  'positions': 'Workforce',
  'positions_list': 'Workforce',
  'department': 'Workforce',
  'departments': 'Workforce',
  'division': 'Workforce',
  'divisions': 'Workforce',
  'competency': 'Workforce',
  'competencies': 'Workforce',
  'qualifications': 'Workforce',
  'responsibilities': 'Workforce',
  'org_structure': 'Workforce',
  'org_changes': 'Workforce',
  'headcount': 'Workforce',
  'headcount_requests': 'Workforce',
  'headcount_forecast': 'Workforce',
  'offboarding': 'Workforce',
  'workforce_analytics': 'Workforce',
  'workforce_forecasting': 'Workforce',
  'capability_registry': 'Workforce',
  'company_boards': 'Workforce',
  'governance': 'Workforce',
  'position_control': 'Workforce',

  // Payroll Module
  'payroll': 'Payroll',
  'payroll_processing': 'Payroll',
  'payroll_run': 'Payroll',
  'payslip': 'Payroll',
  'payslips': 'Payroll',
  'pay_period': 'Payroll',
  'pay_periods': 'Payroll',
  'pay_groups': 'Payroll',
  'salary_advance': 'Payroll',
  'salary_advances': 'Payroll',
  'payroll_loans': 'Payroll',
  'payroll_templates': 'Payroll',
  'payroll_simulations': 'Payroll',
  'payroll_budgeting': 'Payroll',
  'payroll_reports': 'Payroll',
  'payroll_dashboard': 'Payroll',
  'payroll_holidays': 'Payroll',
  'tax_config': 'Payroll',
  'tax_settings': 'Payroll',
  'tax_relief': 'Payroll',
  'tax_allowances': 'Payroll',
  'statutory_deductions': 'Payroll',
  'deductions': 'Payroll',
  'regular_deductions': 'Payroll',
  'bank_file': 'Payroll',
  'batch_operations': 'Payroll',
  'multi_company_consolidation': 'Payroll',
  'integration_webhooks': 'Payroll',
  'severance_calculator': 'Payroll',
  'time_attendance_integration': 'Payroll',
  'vacation_manager': 'Payroll',
  'variable_compensation': 'Payroll',
  'off_cycle_payroll': 'Payroll',
  'opening_balances': 'Payroll',
  'overpayment_recovery': 'Payroll',
  'retroactive_pay': 'Payroll',
  'year_end_processing': 'Payroll',
  'historical_payroll_import': 'Payroll',
  'gl_mapping': 'Payroll',
  'savings_programs': 'Payroll',
  'tip_pool': 'Payroll',
  'expense_claims_payroll': 'Payroll',
  'leave_balance_buyout': 'Payroll',
  'leave_payment_config': 'Payroll',
  'country_payroll': 'Payroll',

  // Compensation Module
  'compensation': 'Compensation',
  'salary': 'Compensation',
  'salary_grades': 'Compensation',
  'salary_grade': 'Compensation',
  'pay_elements': 'Compensation',
  'pay_equity': 'Compensation',
  'bonus': 'Compensation',
  'bonus_management': 'Compensation',
  'equity_management': 'Compensation',
  'merit_cycles': 'Compensation',
  'market_benchmarking': 'Compensation',
  'compa_ratio': 'Compensation',
  'compensation_history': 'Compensation',
  'compensation_analytics': 'Compensation',
  'compensation_budgets': 'Compensation',
  'compensation_dashboard': 'Compensation',
  'minimum_wage': 'Compensation',
  'position_compensation': 'Compensation',
  'position_budget': 'Compensation',
  'spinal_points': 'Compensation',
  'total_rewards': 'Compensation',

  // Benefits Module
  'benefit': 'Benefits',
  'benefits': 'Benefits',
  'benefit_plan': 'Benefits',
  'benefit_plans': 'Benefits',
  'benefit_enrollment': 'Benefits',
  'benefit_enrollments': 'Benefits',
  'benefit_claims': 'Benefits',
  'benefit_categories': 'Benefits',
  'benefit_providers': 'Benefits',
  'benefit_analytics': 'Benefits',
  'benefit_calculator': 'Benefits',
  'benefit_compliance': 'Benefits',
  'benefit_cost_projections': 'Benefits',
  'auto_enrollment_rules': 'Benefits',
  'eligibility_audit': 'Benefits',
  'life_event': 'Benefits',
  'life_events': 'Benefits',
  'open_enrollment': 'Benefits',
  'plan_comparison': 'Benefits',
  'waiting_period': 'Benefits',
  'benefits_dashboard': 'Benefits',

  // Leave Module
  'leave': 'Leave',
  'leave_request': 'Leave',
  'leave_requests': 'Leave',
  'leave_balance': 'Leave',
  'leave_balances': 'Leave',
  'leave_type': 'Leave',
  'leave_types': 'Leave',
  'leave_accrual': 'Leave',
  'leave_accrual_rules': 'Leave',
  'leave_approvals': 'Leave',
  'leave_adjustments': 'Leave',
  'leave_analytics': 'Leave',
  'leave_blackout': 'Leave',
  'leave_calendar': 'Leave',
  'leave_compliance': 'Leave',
  'leave_conflict_rules': 'Leave',
  'leave_dashboard': 'Leave',
  'leave_encashment': 'Leave',
  'leave_holidays': 'Leave',
  'leave_liability': 'Leave',
  'leave_prorata': 'Leave',
  'leave_rollover': 'Leave',
  'leave_schedule': 'Leave',
  'leave_years': 'Leave',
  'maternity_leave': 'Leave',
  'comp_time': 'Leave',
  'compensatory_time': 'Leave',

  // Time & Attendance Module
  'time_attendance': 'Time & Attendance',
  'time_entry': 'Time & Attendance',
  'time_entries': 'Time & Attendance',
  'attendance': 'Time & Attendance',
  'attendance_records': 'Time & Attendance',
  'attendance_analytics': 'Time & Attendance',
  'attendance_exceptions': 'Time & Attendance',
  'attendance_policies': 'Time & Attendance',
  'attendance_regularization': 'Time & Attendance',
  'shift': 'Time & Attendance',
  'shifts': 'Time & Attendance',
  'shift_management': 'Time & Attendance',
  'shift_swaps': 'Time & Attendance',
  'schedule': 'Time & Attendance',
  'schedules': 'Time & Attendance',
  'overtime': 'Time & Attendance',
  'overtime_management': 'Time & Attendance',
  'overtime_alerts': 'Time & Attendance',
  'timesheet': 'Time & Attendance',
  'timesheets': 'Time & Attendance',
  'timesheet_approvals': 'Time & Attendance',
  'time_tracking': 'Time & Attendance',
  'time_audit_trail': 'Time & Attendance',
  'timeclock_devices': 'Time & Attendance',
  'punch_import': 'Time & Attendance',
  'geofence': 'Time & Attendance',
  'flex_time': 'Time & Attendance',
  'live_attendance': 'Time & Attendance',
  'project_time_tracking': 'Time & Attendance',
  'absenteeism_cost': 'Time & Attendance',
  'labor_compliance': 'Time & Attendance',
  'cba_time_rules': 'Time & Attendance',
  'wellness_monitoring': 'Time & Attendance',
  'time_attendance_dashboard': 'Time & Attendance',

  // Performance Module
  'performance': 'Performance',
  'performance_goal': 'Performance',
  'performance_goals': 'Performance',
  'goal': 'Performance',
  'goals': 'Performance',
  'appraisal': 'Performance',
  'appraisals': 'Performance',
  'goal_template': 'Performance',
  'calibration': 'Performance',
  'calibration_session': 'Performance',
  'continuous_feedback': 'Performance',
  'feedback': 'Performance',
  'performance_dashboard': 'Performance',
  'performance_setup': 'Performance',
  'pip': 'Performance',
  'performance_improvement_plan': 'Performance',
  'recognition_awards': 'Performance',
  'review_360': 'Performance',
  'talent_dashboard': 'Performance',
  'performance_intelligence': 'Performance',

  // Recruitment Module
  'recruitment': 'Recruitment',
  'requisition': 'Recruitment',
  'requisitions': 'Recruitment',
  'candidate': 'Recruitment',
  'candidates': 'Recruitment',
  'application': 'Recruitment',
  'applications': 'Recruitment',
  'offer': 'Recruitment',
  'offers': 'Recruitment',
  'interview': 'Recruitment',
  'interviews': 'Recruitment',
  'interview_panels': 'Recruitment',
  'job_board': 'Recruitment',
  'job_boards': 'Recruitment',
  'scorecards': 'Recruitment',
  'assessments': 'Recruitment',
  'sources': 'Recruitment',
  'referrals': 'Recruitment',
  'pipeline': 'Recruitment',
  'email_templates': 'Recruitment',
  'recruitment_analytics': 'Recruitment',
  'recruitment_dashboard': 'Recruitment',

  // Training Module
  'training': 'Training',
  'course': 'Training',
  'courses': 'Training',
  'course_catalog': 'Training',
  'certification': 'Training',
  'certifications': 'Training',
  'learning_path': 'Training',
  'learning_paths': 'Training',
  'training_request': 'Training',
  'training_requests': 'Training',
  'instructor': 'Training',
  'instructors': 'Training',
  'live_session': 'Training',
  'live_sessions': 'Training',
  'training_analytics': 'Training',
  'training_budgets': 'Training',
  'training_calendar': 'Training',
  'training_dashboard': 'Training',
  'training_evaluations': 'Training',
  'training_needs': 'Training',
  'compliance_training': 'Training',
  'competency_gap_analysis': 'Training',
  'content_authoring': 'Training',
  'course_competencies': 'Training',
  'external_training': 'Training',
  'interactive_training': 'Training',
  'mentorship': 'Training',
  'recertification': 'Training',
  'virtual_classroom': 'Training',
  'quiz': 'Training',
  'my_learning': 'Training',
  'career_paths': 'Training',

  // Succession Module
  'succession': 'Succession',
  'succession_plan': 'Succession',
  'succession_plans': 'Succession',
  'succession_dashboard': 'Succession',
  'succession_analytics': 'Succession',
  'talent_pool': 'Succession',
  'talent_pools': 'Succession',
  'key_positions': 'Succession',
  'bench_strength': 'Succession',
  'nine_box': 'Succession',
  'flight_risk': 'Succession',
  'career_development': 'Succession',

  // HSE Module
  'hse': 'HSE',
  'hse_incident': 'HSE',
  'hse_incidents': 'HSE',
  'hse_inspection': 'HSE',
  'hse_inspections': 'HSE',
  'hse_risk_assessment': 'HSE',
  'hse_training': 'HSE',
  'hse_analytics': 'HSE',
  'hse_dashboard': 'HSE',
  'hse_chemicals': 'HSE',
  'hse_compliance': 'HSE',
  'hse_emergency_response': 'HSE',
  'hse_ergonomics': 'HSE',
  'hse_first_aid': 'HSE',
  'hse_loto': 'HSE',
  'hse_near_miss': 'HSE',
  'hse_osha': 'HSE',
  'hse_ppe': 'HSE',
  'hse_permit_to_work': 'HSE',
  'hse_safety_observations': 'HSE',
  'hse_safety_policies': 'HSE',
  'hse_toolbox_talks': 'HSE',
  'hse_workers_comp': 'HSE',

  // Employee Relations Module
  'employee_relations': 'Employee Relations',
  'er_case': 'Employee Relations',
  'er_cases': 'Employee Relations',
  'grievance': 'Employee Relations',
  'grievances': 'Employee Relations',
  'disciplinary': 'Employee Relations',
  'disciplinary_action': 'Employee Relations',
  'union': 'Employee Relations',
  'unions': 'Employee Relations',
  'cba': 'Employee Relations',
  'collective_bargaining': 'Employee Relations',
  'exit_interview': 'Employee Relations',
  'exit_interviews': 'Employee Relations',
  'survey': 'Employee Relations',
  'surveys': 'Employee Relations',
  'wellness': 'Employee Relations',
  'recognition': 'Employee Relations',
  'court_judgements': 'Employee Relations',
  'er_analytics': 'Employee Relations',
  'er_dashboard': 'Employee Relations',

  // Property Module
  'property': 'Property',
  'property_asset': 'Property',
  'property_assets': 'Property',
  'property_assignment': 'Property',
  'property_assignments': 'Property',
  'property_category': 'Property',
  'property_categories': 'Property',
  'property_maintenance': 'Property',
  'property_request': 'Property',
  'property_requests': 'Property',
  'property_analytics': 'Property',
  'property_dashboard': 'Property',

  // ESS Module
  'ess': 'ESS',
  'my_profile': 'ESS',
  'my_leave': 'ESS',
  'my_time': 'ESS',
  'my_benefits': 'ESS',
  'my_training': 'ESS',
  'my_goals': 'ESS',
  'my_compensation': 'ESS',
  'my_documents': 'ESS',
  'my_banking': 'ESS',
  'my_dependents': 'ESS',
  'my_qualifications': 'ESS',
  'my_development_plan': 'ESS',
  'my_expense_claims': 'ESS',
  'my_feedback': 'ESS',
  'my_recognition': 'ESS',
  'my_reminders': 'ESS',
  'my_timesheets': 'ESS',
  'my_transactions': 'ESS',
  'my_appraisals': 'ESS',
  'my_career_plan': 'ESS',
  'my_competencies': 'ESS',
  'my_evidence_portfolio': 'ESS',
  'my_government_ids': 'ESS',
  'my_hse': 'ESS',
  'my_immigration': 'ESS',
  'my_interests': 'ESS',
  'my_letters': 'ESS',
  'my_medical_info': 'ESS',
  'my_mentorship': 'ESS',
  'my_offboarding': 'ESS',
  'my_onboarding': 'ESS',
  'my_personal_info': 'ESS',
  'my_professional_info': 'ESS',
  'my_property': 'ESS',
  'my_skill_gaps': 'ESS',
  'my_calendar': 'ESS',
  'employee_self_service': 'ESS',
  'job_openings': 'ESS',
  'milestones': 'ESS',
  'notification_preferences': 'ESS',
  'team_calendar': 'ESS',

  // MSS Module
  'mss': 'MSS',
  'team': 'MSS',
  'team_member': 'MSS',
  'manager_self_service': 'MSS',
  'mss_analytics': 'MSS',
  'mss_appraisals': 'MSS',
  'mss_benefits': 'MSS',
  'mss_calibration': 'MSS',
  'mss_compensation': 'MSS',
  'mss_development_plans': 'MSS',
  'mss_employee_relations': 'MSS',
  'mss_equity': 'MSS',
  'mss_feedback': 'MSS',
  'mss_goals': 'MSS',
  'mss_hse': 'MSS',
  'mss_leave': 'MSS',
  'mss_offboarding': 'MSS',
  'mss_onboarding': 'MSS',
  'mss_payroll': 'MSS',
  'mss_pips': 'MSS',
  'mss_property': 'MSS',
  'mss_recognition': 'MSS',
  'mss_recruitment': 'MSS',
  'mss_reminders': 'MSS',
  'mss_review_360': 'MSS',
  'mss_succession': 'MSS',
  'mss_time_attendance': 'MSS',
  'mss_training': 'MSS',

  // Documents Module
  'document': 'Documents',
  'documents': 'Documents',

  // Reporting Module
  'report': 'Reporting',
  'reports': 'Reporting',
  'analytics': 'Reporting',

  // Profile
  'profile': 'Profile',
  'profiles': 'Profile',

  // Security
  'security': 'Security',
  'auth': 'Security',
  'login': 'Security',
  'logout': 'Security',
};

export const availableModules = [
  'Admin',
  'Workforce',
  'Payroll',
  'Compensation',
  'Benefits',
  'Leave',
  'Time & Attendance',
  'Performance',
  'Recruitment',
  'Training',
  'Succession',
  'HSE',
  'Employee Relations',
  'Property',
  'ESS',
  'MSS',
  'Documents',
  'Reporting',
  'Profile',
  'Security',
];

/**
 * Get the module name for a given entity type
 */
export function getModuleFromEntityType(entityType: string): string {
  // Direct lookup
  if (moduleMapping[entityType]) {
    return moduleMapping[entityType];
  }

  // Try lowercase
  const lowerType = entityType.toLowerCase();
  if (moduleMapping[lowerType]) {
    return moduleMapping[lowerType];
  }

  // Pattern matching for common prefixes
  for (const [key, module] of Object.entries(moduleMapping)) {
    if (lowerType.startsWith(key) || lowerType.includes(key)) {
      return module;
    }
  }

  return 'Other';
}

/**
 * Get all entity types for a given module
 */
export function getEntityTypesForModule(moduleName: string): string[] {
  return Object.entries(moduleMapping)
    .filter(([_, module]) => module === moduleName)
    .map(([entityType]) => entityType);
}
